export const categories = [
  'All blocks',
  'Hero',
  'Features',
  'Pricing',
  'Testimonials',
  'Forms',
  'Checkout Forms',
  'Stats',
  'CTA',
  'Blog',
  'Navbars',
  'Sidebars',
  'Command Palettes',
  'Tables',
  'Product Overviews',
  'Product Lists',
  'Shopping Carts',
] as const
